/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.demo.workflow.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Hotel service. Represents a row in the &quot;demo_Hotel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.demo.workflow.core.model.impl.HotelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.demo.workflow.core.model.impl.HotelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Hotel
 * @see com.demo.workflow.core.model.impl.HotelImpl
 * @see com.demo.workflow.core.model.impl.HotelModelImpl
 * @generated
 */
@ProviderType
public interface HotelModel extends BaseModel<Hotel>, GroupedModel, ShardedModel,
	StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hotel model instance should use the {@link Hotel} interface instead.
	 */

	/**
	 * Returns the primary key of this hotel.
	 *
	 * @return the primary key of this hotel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hotel.
	 *
	 * @param primaryKey the primary key of this hotel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this hotel.
	 *
	 * @return the uuid of this hotel
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this hotel.
	 *
	 * @param uuid the uuid of this hotel
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the order ID of this hotel.
	 *
	 * @return the order ID of this hotel
	 */
	public long getOrderId();

	/**
	 * Sets the order ID of this hotel.
	 *
	 * @param orderId the order ID of this hotel
	 */
	public void setOrderId(long orderId);

	/**
	 * Returns the group ID of this hotel.
	 *
	 * @return the group ID of this hotel
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this hotel.
	 *
	 * @param groupId the group ID of this hotel
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this hotel.
	 *
	 * @return the company ID of this hotel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this hotel.
	 *
	 * @param companyId the company ID of this hotel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this hotel.
	 *
	 * @return the user ID of this hotel
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this hotel.
	 *
	 * @param userId the user ID of this hotel
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this hotel.
	 *
	 * @return the user uuid of this hotel
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this hotel.
	 *
	 * @param userUuid the user uuid of this hotel
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this hotel.
	 *
	 * @return the user name of this hotel
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this hotel.
	 *
	 * @param userName the user name of this hotel
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this hotel.
	 *
	 * @return the create date of this hotel
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this hotel.
	 *
	 * @param createDate the create date of this hotel
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this hotel.
	 *
	 * @return the modified date of this hotel
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this hotel.
	 *
	 * @param modifiedDate the modified date of this hotel
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the pizza of this hotel.
	 *
	 * @return the pizza of this hotel
	 */
	public int getPizza();

	/**
	 * Sets the pizza of this hotel.
	 *
	 * @param pizza the pizza of this hotel
	 */
	public void setPizza(int pizza);

	/**
	 * Returns the burger of this hotel.
	 *
	 * @return the burger of this hotel
	 */
	public int getBurger();

	/**
	 * Sets the burger of this hotel.
	 *
	 * @param burger the burger of this hotel
	 */
	public void setBurger(int burger);

	/**
	 * Returns the doughnut of this hotel.
	 *
	 * @return the doughnut of this hotel
	 */
	public int getDoughnut();

	/**
	 * Sets the doughnut of this hotel.
	 *
	 * @param Doughnut the doughnut of this hotel
	 */
	public void setDoughnut(int Doughnut);

	/**
	 * Returns the status of this hotel.
	 *
	 * @return the status of this hotel
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this hotel.
	 *
	 * @param status the status of this hotel
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this hotel.
	 *
	 * @return the status by user ID of this hotel
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this hotel.
	 *
	 * @param statusByUserId the status by user ID of this hotel
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this hotel.
	 *
	 * @return the status by user uuid of this hotel
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this hotel.
	 *
	 * @param statusByUserUuid the status by user uuid of this hotel
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this hotel.
	 *
	 * @return the status by user name of this hotel
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this hotel.
	 *
	 * @param statusByUserName the status by user name of this hotel
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this hotel.
	 *
	 * @return the status date of this hotel
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this hotel.
	 *
	 * @param statusDate the status date of this hotel
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns <code>true</code> if this hotel is approved.
	 *
	 * @return <code>true</code> if this hotel is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this hotel is denied.
	 *
	 * @return <code>true</code> if this hotel is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this hotel is a draft.
	 *
	 * @return <code>true</code> if this hotel is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this hotel is expired.
	 *
	 * @return <code>true</code> if this hotel is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this hotel is inactive.
	 *
	 * @return <code>true</code> if this hotel is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this hotel is incomplete.
	 *
	 * @return <code>true</code> if this hotel is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this hotel is pending.
	 *
	 * @return <code>true</code> if this hotel is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this hotel is scheduled.
	 *
	 * @return <code>true</code> if this hotel is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Hotel hotel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Hotel> toCacheModel();

	@Override
	public Hotel toEscapedModel();

	@Override
	public Hotel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}