/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.demo.workflow.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Leave service. Represents a row in the &quot;demo_Leave&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.demo.workflow.core.model.impl.LeaveModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.demo.workflow.core.model.impl.LeaveImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Leave
 * @see com.demo.workflow.core.model.impl.LeaveImpl
 * @see com.demo.workflow.core.model.impl.LeaveModelImpl
 * @generated
 */
@ProviderType
public interface LeaveModel extends BaseModel<Leave>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave model instance should use the {@link Leave} interface instead.
	 */

	/**
	 * Returns the primary key of this leave.
	 *
	 * @return the primary key of this leave
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave.
	 *
	 * @param primaryKey the primary key of this leave
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave.
	 *
	 * @return the uuid of this leave
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave.
	 *
	 * @param uuid the uuid of this leave
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave ID of this leave.
	 *
	 * @return the leave ID of this leave
	 */
	public long getLeaveId();

	/**
	 * Sets the leave ID of this leave.
	 *
	 * @param leaveId the leave ID of this leave
	 */
	public void setLeaveId(long leaveId);

	/**
	 * Returns the group ID of this leave.
	 *
	 * @return the group ID of this leave
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this leave.
	 *
	 * @param groupId the group ID of this leave
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave.
	 *
	 * @return the company ID of this leave
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave.
	 *
	 * @param companyId the company ID of this leave
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this leave.
	 *
	 * @return the user ID of this leave
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this leave.
	 *
	 * @param userId the user ID of this leave
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave.
	 *
	 * @return the user uuid of this leave
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this leave.
	 *
	 * @param userUuid the user uuid of this leave
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this leave.
	 *
	 * @return the user name of this leave
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this leave.
	 *
	 * @param userName the user name of this leave
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this leave.
	 *
	 * @return the create date of this leave
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave.
	 *
	 * @param createDate the create date of this leave
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave.
	 *
	 * @return the modified date of this leave
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave.
	 *
	 * @param modifiedDate the modified date of this leave
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the leave name of this leave.
	 *
	 * @return the leave name of this leave
	 */
	@AutoEscape
	public String getLeaveName();

	/**
	 * Sets the leave name of this leave.
	 *
	 * @param leaveName the leave name of this leave
	 */
	public void setLeaveName(String leaveName);

	/**
	 * Returns the start date of this leave.
	 *
	 * @return the start date of this leave
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this leave.
	 *
	 * @param startDate the start date of this leave
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this leave.
	 *
	 * @return the end date of this leave
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this leave.
	 *
	 * @param endDate the end date of this leave
	 */
	public void setEndDate(Date endDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Leave leave);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Leave> toCacheModel();

	@Override
	public Leave toEscapedModel();

	@Override
	public Leave toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}